apiVersion: xl-deploy/v1
kind: Roles
spec:
  - name: Developers
    principals:
      - oidc-developers
---
apiVersion: xl-deploy/v1
kind: Permissions
spec:
  - global:
      - role: Developers
        permissions:
          - login
          - admin
